TAIsRich/chuwa0403

Coding/coding1/EncapsulationDemo.java, Coding/coding1/InheritanceExample.java, Coding/coding1/ParkingLot/Car.java, Coding/coding1/ParkingLot/ParkingLot.java, Coding/coding1/ParkingLot/ParkingSpot.java, Coding/coding1/ParkingLot/Truck.java, Coding/coding1/ParkingLot/Vehicle.java, Coding/coding1/PolymorphismDemo.java, ShortQuestions/hw2.md
I don't know why the code don't show in coding1 file
=> Qiuchen lei/hw2

Coding/coding1/ParkingLot.java, MavenProject/hw1Maven/pom.xml, ShortQuestions/README.md, ShortQuestions/hw1.md, ShortQuestions/hw2.md
=> Chen yuan/hw2

Coding/hw2_Encapsulation.java, Coding/hw2_Inheritance.java, Coding/hw2_Polymorphism.java, Coding/parking_lot.java, MavenProject/pom.xml, ShortQuestions/ReadMe.md, ShortQuestions/hw1.md, ShortQuestions/hw2.md
=> Zilu huang/hw2

MavenProject/com.chuwa.learn/pom.xml, ShortQuestions/hw1.md
Sorry for the late submission. My computer's broken this week. I just got a new labtop on Sunday.
=> finish hw1

Coding/coding1/Customer.java, Coding/coding1/ParkingLot.java, Coding/coding1/ParkingRecord.java, Coding/coding1/Record.java, Coding/coding1/Vehicle.java, MavenProject/pom.xml, MavenProject/src/main/java/hw2/encapsulation/Encapsulation.java, MavenProject/src/main/java/hw2/inheritance/Hobby.java, MavenProject/src/main/java/hw2/inheritance/Main.java, MavenProject/src/main/java/hw2/inheritance/People.java, MavenProject/src/main/java/hw2/inheritance/School.java, MavenProject/src/main/java/hw2/inheritance/Student.java, MavenProject/src/main/java/hw2/inheritance/Worker.java, MavenProject/src/main/java/hw2/polymorphism/Main.java, MavenProject/src/main/java/hw2/polymorphism/People.java, ShortQuestions/README.md, ShortQuestions/hw1.md, ShortQuestions/hw2.md
=> Jiayi liang/hw2

MavenProject/pom.xml, ShortQuestions/README.md, ShortQuestions/hw1.md
Here is my homework 1. Thank you :)
=> Jiayi_Liang/hw1

Coding/coding1/.gitignore, Coding/coding1/pom.xml, Coding/coding1/src/main/java/org/example/Main.java, MavenProject/Hw1/.gitignore, MavenProject/Hw1/pom.xml, MavenProject/Hw1/src/main/java/com/chuwa/learn/Main.java, MavenProject/Hw1/src/main/java/org/example/Main.java, ShortQuestions/README.md, ShortQuestions/hw1.md, ShortQuestions/hw2.md
=> Jeremy zhuang/hw2

Coding/coding1/.gitignore, Coding/coding1/pom.xml, Coding/coding1/src/main/java/org/example/Main.java, MavenProject/Hw1/.gitignore, MavenProject/Hw1/pom.xml, MavenProject/Hw1/src/main/java/com/chuwa/learn/Main.java, MavenProject/Hw1/src/main/java/org/example/Main.java, ShortQuestions/README.md, ShortQuestions/hw1.md, ShortQuestions/hw2.md
- MavenProject/Hw1/.gitignore
- MavenProject/Hw1/pom.xml
- MavenProject/Hw1/src/main/java/org/example/Main.java
- ShortQuestions/README.md
- ShortQuestions/hw1.md
=> Jeremy zhuang/hw1

Coding/ParkingLot.java, Coding/ParkingSpot.java, Coding/Vehicle.java, Coding/placeholder.txt, ShortQuestions/hw2.md, ShortQuestions/placeholder.txt
=> Zhufeng chen/hw2

MavenProject/maven/pom.xml, MavenProject/maven/src/main/resources/META-INF/maven/archetype.xml, MavenProject/maven/src/main/resources/archetype-resources/pom.xml, MavenProject/maven/src/main/resources/archetype-resources/src/main/java/App.java, MavenProject/maven/src/main/resources/archetype-resources/src/test/java/AppTest.java, ShortQuestions/README.md, ShortQuestions/hw1.md
=> HW1 submit

Coding/Example.java, Coding/ParkingLot.java, HW2.md
=> Answers for HW2

Coding/ParkingLot/src/Main.java, Coding/ParkingLot/src/ParkingLot.java, Coding/ParkingLot/src/ParkingSpot.java, Coding/ParkingLot/src/Vehicle.java, Coding/hw2/src/Circle.java, Coding/hw2/src/Main.java, Coding/hw2/src/Rectangle.java, Coding/hw2/src/Shape.java, Coding/hw2/src/TwoDGeometricObject.java, Coding/hw2/src/TwoDShape.java, ShortQuestions/hw2.md, ShortQuestions/placeholder.txt
=> Haotian Zhu/hw2

ShortQuestions/hw1.md
=> Anmin huang/hw1

MavenProject/pom.xml, ShortQuestions/README.md, hw1.md
This changes is about answers for HW1 Q1-Q13
No test applies.
=> Answers for HW1 Q1-13

MavenProject/java-core/pom.xml, MavenProject/java-core/src/main/java/com/chuwa/learn/App.java, MavenProject/java-core/src/test/java/com/chuwa/learn/AppTest.java, ShortQuestions/README.md, ShortQuestions/hw1.md
=> Jiale huang/hw1

MavenProject/TestMavenModule/pom.xml, MavenProject/TestMavenModule/src/main/java/com/chuwa/learn/Main.java, ShortQuestions/README.md, ShortQuestions/hw1.md
=> hw1-cirun zhang

MavenPorject/MavenModule/pom.xml, MavenPorject/MavenModule/src/main/java/org/example/App.java, MavenPorject/MavenModule/src/test/java/org/example/AppTest.java, ShortQuestions/README.md, ShortQuestions/hw1.md
1. ShortQuestions/README.md
2. ShortQuestions/hw1.md
3. MavenPorject/MavenModule/pom.xml
=> Haotian Zhu/HW1

MavenProject/pom.xml, MavenProject/src/main/java/com/chuwa/learn/Main.java, ShortQuestions/README.md, ShortQuestions/hw1.md
=> Chiehmin chung/hw1

Coding/exercise/Customer.java, Coding/exercise/EmptyCartException.java, Coding/exercise/Item.java, Coding/exercise/ShoppingCart.java, Coding/exercise/ShoppingCartAnswer.java, Coding/exercise/ShoppingCartUtil.java, Coding/features/Employee.java, Coding/features/EmployeeData.java, Coding/features/default_interface_method/Client.java, Coding/features/default_interface_method/DIMImpl.java, Coding/features/default_interface_method/DIML.java, Coding/features/lambda/Foo.java, Coding/features/lambda/LambdaLearn.java, Coding/features/method_reference/MethodReferenceExample.java, Coding/features/optional/OptionalDemo.java, Coding/features/optional/OptionalMainMethodTest.java, Coding/features/optional/OptionalTest.java, Coding/features/stream_api/Product.java, Coding/features/stream_api/ProductClient.java, Coding/features/stream_api/StreamApiCreationTest.java, Coding/features/stream_api/StreamApiEndOperation.java, Coding/features/stream_api/StreamApiIntermediateOperation.java, Coding/features/stream_api/StreamExercise.java, Coding/generic/GenericClass.java, Coding/generic/GenericClassTest.java, Coding/generic/GenericMethod.java, Coding/generic/GenericMultiArguments.java, Coding/generic/NonGeneric.java, ShortQuestions/hw5.md
=> Chen yuan/hw5

Coding/hw5/Generic/GenericClass.java, Coding/hw5/Generic/GenericClassTest.java, Coding/hw5/Generic/GenericMethod.java, Coding/hw5/Generic/GenericMultiArguments.java, Coding/hw5/Generic/NonGeneric.java, Coding/hw5/StreamApiTest2.java, Coding/hw5/java8practise/src/exercise/Customer.java, Coding/hw5/java8practise/src/exercise/EmptyCartException.java, Coding/hw5/java8practise/src/exercise/Item.java, Coding/hw5/java8practise/src/exercise/ShoppingCart.java, Coding/hw5/java8practise/src/exercise/ShoppingCartUtil.java, Coding/hw5/java8practise/src/features/common/pojos/Employee.java, Coding/hw5/java8practise/src/features/common/utils/EmployeeData.java, Coding/hw5/java8practise/src/features/interface_method/Client.java, Coding/hw5/java8practise/src/features/interface_method/DIMImpl.java, Coding/hw5/java8practise/src/features/interface_method/DIML.java, Coding/hw5/java8practise/src/features/lambda/Foo.java, Coding/hw5/java8practise/src/features/lambda/LambdaLearn.java, Coding/hw5/java8practise/src/features/method_reference/MethodReferenceExample.java, Coding/hw5/java8practise/src/features/optional/OptionalDemo.java, Coding/hw5/java8practise/src/features/optional/OptionalMainMethodTest.java, Coding/hw5/java8practise/src/features/optional/OptionalTest.java, Coding/hw5/java8practise/src/features/stream_api/Product.java, Coding/hw5/java8practise/src/features/stream_api/ProductClient.java, Coding/hw5/java8practise/src/features/stream_api/StreamApiCreationTest.java, Coding/hw5/java8practise/src/features/stream_api/StreamApiEndOperation.java, Coding/hw5/java8practise/src/features/stream_api/StreamApiIntermediateOperation.java, Coding/hw5/java8practise/src/features/stream_api/StreamExercise.java, ShortQuestions/hw5.md
=> Min he/hw5

Coding/HW6Q25/MergeAPI.java, Coding/HW6Q25/twoSumAndProductCompFuture.java, Coding/HW6multithreading/basic_thread_handling/Daemon.java, Coding/HW6multithreading/basic_thread_handling/InterruptTest.java, Coding/HW6multithreading/basic_thread_handling/JoinTest.java, Coding/HW6multithreading/basic_thread_handling/SleepTest.java, Coding/HW6multithreading/create/CallableTest.java, Coding/HW6multithreading/create/Main.java, Coding/HW6multithreading/create/MyCallable.java, Coding/HW6multithreading/create/MyRunnable.java, Coding/HW6multithreading/create/MyThread.java, Coding/HW6multithreading/deadlock/DeadLock.java, Coding/HW6multithreading/executor_framework/ThreadPoolExample.java, Coding/HW6multithreading/executor_framework/WebCrawlerExample.java, Coding/HW6multithreading/forkjoin/ForkJoinLearn.java, Coding/HW6multithreading/syncronized_theads/SynchronizedThreads.java, Coding/HW6multithreading/syncronized_theads/SynchronizedThreadsFailed.java, Coding/HW6multithreading/threadlocal/ThreadLocalLearn.java, Coding/HW6multithreading/util_concurrent_locks/AtomicLearn.java, Coding/HW6multithreading/util_concurrent_locks/ConcurrentCollection.java, Coding/HW6multithreading/util_concurrent_locks/ConditionLearn.java, Coding/HW6multithreading/util_concurrent_locks/ReadWriteLockLearn.java, Coding/HW6multithreading/util_concurrent_locks/ReentrantLockLearn.java, Coding/HW6multithreading/util_concurrent_locks/StampedLockLearn.java, Coding/HW6multithreading/waitnotify/OddEventPrinter.java, Coding/HW6multithreading/waitnotify/WaitNotify.java, ShortQuestions/hw6.md
=> Chen yuan/hw6

Coding/hw6/OddEvenPrinterReentrantLock.java, Coding/hw6/OddEvenPrinterSynchronized.java, Coding/hw6/PrintNumber.java, Coding/hw6/completableFuture/homework1/CompletableFutureO.java, Coding/hw6/completableFuture/homework1/SumProduct.java, Coding/hw6/completableFuture/homework3/OnlineStore2.java, Coding/hw6/completableFuture/howework2/OnlineStore.java, ShortQuestions/hw6.md
=> Min he/hw6

ShortQuestions/hw6.md, java-core/src/main/java/com/chuwa/learn/completablefuture/CompletableFutureExample.java, java-core/src/main/java/com/chuwa/learn/completablefuture/OnlineStore.java, java-core/src/main/java/com/chuwa/learn/multithreading/OddEvenPrinter2.java, java-core/src/main/java/com/chuwa/learn/multithreading/OddEventPrinter.java, java-core/src/main/java/com/chuwa/learn/multithreading/PrintNumber1.java, stream-api-exercises-main/pom.xml
=> Jianyu chen/hw6

Coding/future25.java, Coding/multithreading.java, Coding/multithreading10.java, Coding/multithreading2.java, Coding/multithreading3.java, Coding/multithreading4.java, Coding/multithreading5.java, Coding/multithreading6.java, Coding/multithreading7.java, Coding/multithreading8.java, Coding/multithreading9.java, Coding/thread23.java, Coding/thread23b.java, Coding/thread24.java, ShortQuestions/hw6.md
=> Zilu Huang hw6

ShortQuestions/annotations.md, ShortQuestions/hw10.md, ShortQuestions/hw9.md
=> Min he/hw10

ShortQuestions/hw10.md
=> qiuchen_hw10

ShortQuestions/annotation.md, ShortQuestions/hw-exception-validation-basic-mvc.md, ShortQuestions/hw10.md
=> Chen yuan/hw10

Coding/placeholder.txt, ShortQuestions/hw10.md, ShortQuestions/placeholder.txt
=> submit hw10

ShortQuestions/hw-exception-validation-basic-mvc.md
=> hw-exception-validation-basic-mvc.md

ShortQuestions/hw9.md
=> qiuchen hw9

Coding/hw12/CommentServiceImplTest.java, ShortQuestions/annotations.md, ShortQuestions/hw11.md, ShortQuestions/hw12.md
=> Min he/hw12

ShortQuestions/annotations.md, ShortQuestions/hw11.md
=> min_he/hw11

ShortQuestions/annotation.md, ShortQuestions/hw11.md
=> Chen yuan/hw11

ShortQuestions/hw12.md
=> qiuchen_hw12

ShortQuestions/hw11.md, ShortQuestions/hw12.md, redbook/pom.xml, redbook/src/main/java/com/chuwa/redbook/aop/LoggingAspect.java, redbook/src/main/java/com/chuwa/redbook/aop/WebLog.java, redbook/src/main/java/com/chuwa/redbook/aop/WebLogAspect.java, redbook/src/main/java/com/chuwa/redbook/controller/PostController.java, redbook/src/main/java/com/chuwa/redbook/service/impl/CommentServiceImpl.java, redbook/src/test/java/com/chuwa/redbook/service/impl/CommentServiceImplTest.java, redbook/src/test/java/com/chuwa/redbook/service/impl/PostServiceImplTest.java
=> Jianyu chen/hw12

ShortQuestions/hw11.md
=> qiuchen_lei hw11

ShortQuestions/hw13.md, ShortQuestions/hw14.md
=> min_he/hw14

Coding/placeholder.txt, ShortQuestions/hw14.md, ShortQuestions/placeholder.txt
=> Bowei xu/hw14

ShortQuestions/hw12.md
=> hw12 ShortQuestions completed
